/**
 * CI/GitHub Actions integration.
 *
 * Origin: Parent C (agent-sdk-service), simplified to remove Slack Bolt
 * dependency. Uses Parent B's report format for compatibility.
 */

import type { VerificationReport } from "./invariant-engine.js";

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

export interface CIContext {
  triggerType: "pr" | "schedule" | "manual";
  repo?: string;
  prNumber?: number;
  ref?: string;
  githubToken?: string;
}

// ---------------------------------------------------------------------------
// Context detection
// ---------------------------------------------------------------------------

export function detectCIContext(): CIContext {
  const eventName = process.env.GITHUB_EVENT_NAME;
  const repo = process.env.GITHUB_REPOSITORY;
  const ref = process.env.GITHUB_REF;
  const token = process.env.GITHUB_TOKEN;

  if (eventName === "pull_request" || eventName === "pull_request_target") {
    const prNumber = ref ? parseInt(ref.split("/")[2], 10) : undefined;
    return {
      triggerType: "pr",
      repo,
      prNumber: Number.isNaN(prNumber) ? undefined : prNumber,
      ref,
      githubToken: token,
    };
  }

  if (eventName === "schedule") {
    return { triggerType: "schedule", repo, ref, githubToken: token };
  }

  return { triggerType: "manual", repo, ref, githubToken: token };
}

// ---------------------------------------------------------------------------
// PR Comment formatting
// ---------------------------------------------------------------------------

function severityBadge(severity: string): string {
  const badges: Record<string, string> = {
    critical: "🔴 CRITICAL",
    high: "🟠 HIGH",
    medium: "🟡 MEDIUM",
    low: "🔵 LOW",
  };
  return badges[severity] ?? severity.toUpperCase();
}

export function formatPRComment(report: VerificationReport): string {
  const { summary, results } = report;
  const icon = summary.failed > 0 ? "❌" : "✅";

  const lines: string[] = [
    `## ${icon} Cross-Repo Invariant Check`,
    "",
    `**${summary.passed} passed** | **${summary.failed} failed** | **${summary.errors} errors**`,
    "",
    "| Invariant | Severity | Status | Violations |",
    "|-----------|----------|--------|------------|",
  ];

  for (const r of results) {
    const statusIcon =
      r.status === "pass" ? "✅" : r.status === "fail" ? "❌" : "⚠️";
    lines.push(
      `| \`${r.id}\` | ${r.severity} | ${statusIcon} ${r.status} | ${r.violations.length} |`,
    );
  }

  const failures = results.filter((r) => r.status === "fail");
  if (failures.length > 0) {
    lines.push("", "### Violations", "");
    for (const r of failures) {
      lines.push(`**${r.id}** (${severityBadge(r.severity)})`);
      const limit = Math.min(r.violations.length, 10);
      for (let i = 0; i < limit; i++) {
        const v = r.violations[i];
        lines.push(`- \`${v.repo}\` — \`${v.file}:${v.line}\` — ${v.detail}`);
      }
      if (r.violations.length > 10) {
        lines.push(`- _...and ${r.violations.length - 10} more_`);
      }
      lines.push(`> ${r.message}`, "");
    }
  }

  lines.push("---", "_Generated by Cross-Repo Invariant Verifier_");
  return lines.join("\n");
}

// ---------------------------------------------------------------------------
// PR Comment posting
// ---------------------------------------------------------------------------

export async function postPRComment(payload: {
  owner: string;
  repo: string;
  prNumber: number;
  body: string;
  token: string;
}): Promise<void> {
  const url = `https://api.github.com/repos/${payload.owner}/${payload.repo}/issues/${payload.prNumber}/comments`;

  const response = await fetch(url, {
    method: "POST",
    headers: {
      Authorization: `Bearer ${payload.token}`,
      "Content-Type": "application/json",
      Accept: "application/vnd.github.v3+json",
    },
    body: JSON.stringify({ body: payload.body }),
  });

  if (!response.ok) {
    const text = await response.text();
    throw new Error(`Failed to post PR comment: ${response.status} ${text}`);
  }

  console.error(`[ci] Posted comment to PR #${payload.prNumber}`);
}

// ---------------------------------------------------------------------------
// Exit code logic
// ---------------------------------------------------------------------------

export function exitCodeForReport(report: VerificationReport): number {
  const hasBlocking = report.results.some(
    (r) =>
      r.status === "fail" &&
      (r.severity === "critical" || r.severity === "high"),
  );
  return hasBlocking ? 1 : 0;
}
