/**
 * CI/GitHub Actions integration.
 *
 * Handles:
 * - Posting violation results as PR comments
 * - Reading GitHub Actions event context
 * - Setting exit codes based on violation severity
 */

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

export interface CIContext {
  /** "pr" | "schedule" | "manual" */
  triggerType: "pr" | "schedule" | "manual";
  /** GitHub repository (owner/repo) */
  repo?: string;
  /** PR number (if PR-triggered) */
  prNumber?: number;
  /** Git ref (branch or SHA) */
  ref?: string;
  /** GitHub token for API calls */
  githubToken?: string;
}

export interface PRCommentPayload {
  owner: string;
  repo: string;
  prNumber: number;
  body: string;
  token: string;
}

// ---------------------------------------------------------------------------
// Context detection
// ---------------------------------------------------------------------------

/**
 * Detect CI context from environment variables (GitHub Actions).
 */
export function detectCIContext(): CIContext {
  const eventName = process.env.GITHUB_EVENT_NAME;
  const repo = process.env.GITHUB_REPOSITORY;
  const ref = process.env.GITHUB_REF;
  const token = process.env.GITHUB_TOKEN;

  // PR trigger
  if (eventName === "pull_request" || eventName === "pull_request_target") {
    const prNumber = ref ? parseInt(ref.split("/")[2], 10) : undefined;
    return {
      triggerType: "pr",
      repo,
      prNumber: Number.isNaN(prNumber) ? undefined : prNumber,
      ref,
      githubToken: token,
    };
  }

  // Schedule trigger
  if (eventName === "schedule") {
    return { triggerType: "schedule", repo, ref, githubToken: token };
  }

  // Manual or unknown
  return { triggerType: "manual", repo, ref, githubToken: token };
}

// ---------------------------------------------------------------------------
// PR Comment posting
// ---------------------------------------------------------------------------

import type { VerificationSummary, Violation } from "./slack-notifier.js";

/**
 * Format a verification summary as a GitHub PR comment (Markdown).
 */
export function formatPRComment(summary: VerificationSummary): string {
  const icon = summary.failed > 0 ? "❌" : "✅";
  const lines: string[] = [
    `## ${icon} Cross-Repo Invariant Check`,
    "",
    `| Metric | Value |`,
    `|--------|-------|`,
    `| Invariants checked | ${summary.totalInvariants} |`,
    `| Passed | ${summary.passed} |`,
    `| Failed | ${summary.failed} |`,
    `| Duration | ${(summary.durationMs / 1000).toFixed(1)}s |`,
    "",
  ];

  if (summary.violations.length > 0) {
    lines.push("### Violations", "");
    for (const v of summary.violations) {
      const badge = severityBadge(v.severity);
      lines.push(`- ${badge} **${v.invariantId}** in \`${v.repo}\``);
      lines.push(`  ${v.message}`);
      if (v.details) {
        lines.push(`  _${v.details}_`);
      }
    }
  }

  lines.push("", "---", "_Generated by Cross-Repo Invariant Verifier_");

  return lines.join("\n");
}

function severityBadge(severity: string): string {
  const badges: Record<string, string> = {
    critical: "🔴 CRITICAL",
    high: "🟠 HIGH",
    medium: "🟡 MEDIUM",
    low: "🔵 LOW",
  };
  return badges[severity] ?? severity.toUpperCase();
}

/**
 * Post a comment to a GitHub PR via the REST API.
 */
export async function postPRComment(payload: PRCommentPayload): Promise<void> {
  const url = `https://api.github.com/repos/${payload.owner}/${payload.repo}/issues/${payload.prNumber}/comments`;

  const response = await fetch(url, {
    method: "POST",
    headers: {
      Authorization: `Bearer ${payload.token}`,
      "Content-Type": "application/json",
      Accept: "application/vnd.github.v3+json",
    },
    body: JSON.stringify({ body: payload.body }),
  });

  if (!response.ok) {
    const text = await response.text();
    throw new Error(`Failed to post PR comment: ${response.status} ${text}`);
  }

  console.log(`[CI] Posted comment to PR #${payload.prNumber}`);
}

/**
 * Determine exit code based on violation severities.
 * Critical/high = exit 1 (fail the build), medium/low = exit 0 (warn only).
 */
export function exitCodeForSummary(summary: VerificationSummary): number {
  const hasBlocking = summary.violations.some(
    (v) => v.severity === "critical" || v.severity === "high",
  );
  return hasBlocking ? 1 : 0;
}
