/**
 * CI/GitHub Actions integration.
 *
 * Origin: Parent C (agent-sdk-service), simplified to remove Slack Bolt
 * dependency. Uses Parent B's report format for compatibility.
 */

import type { VerificationReport } from "./invariant-engine.js";

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

export interface CIContext {
  triggerType: "pr" | "schedule" | "manual";
  repo?: string;
  prNumber?: number;
  ref?: string;
  githubToken?: string;
}

// ---------------------------------------------------------------------------
// Context detection
// ---------------------------------------------------------------------------

export function detectCIContext(): CIContext {
  const eventName = process.env.GITHUB_EVENT_NAME;
  const repo = process.env.GITHUB_REPOSITORY;
  const ref = process.env.GITHUB_REF;
  const token = process.env.GITHUB_TOKEN;

  if (eventName === "pull_request" || eventName === "pull_request_target") {
    const prNumber = ref ? parseInt(ref.split("/")[2], 10) : undefined;
    return {
      triggerType: "pr",
      repo,
      prNumber: Number.isNaN(prNumber) ? undefined : prNumber,
      ref,
      githubToken: token,
    };
  }

  if (eventName === "schedule") {
    return { triggerType: "schedule", repo, ref, githubToken: token };
  }

  return { triggerType: "manual", repo, ref, githubToken: token };
}

// ---------------------------------------------------------------------------
// PR Comment formatting
// ---------------------------------------------------------------------------

function severityBadge(severity: string): string {
  const badges: Record<string, string> = {
    critical: "🔴 CRITICAL",
    high: "🟠 HIGH",
    medium: "🟡 MEDIUM",
    low: "🔵 LOW",
  };
  return badges[severity] ?? severity.toUpperCase();
}

export function formatPRComment(report: VerificationReport): string {
  const { summary, results } = report;
  const icon = summary.failed > 0 ? "❌" : "✅";

  const lines: string[] = [
    `## ${icon} Cross-Repo Invariant Check`,
    "",
    `**${summary.passed} passed** | **${summary.failed} failed** | **${summary.errors} errors**`,
    "",
    "| Invariant | Severity | Status | Violations |",
    "|-----------|----------|--------|------------|",
  ];

  for (const r of results) {
    // A canary is only "expected" when it actually fired (status fail);
    // a passing or erroring canary is a broken pipeline and must show as such.
    const canaryFired = r.id.startsWith("canary-") && r.status === "fail";
    const statusIcon = canaryFired
      ? "🔵"
      : r.status === "pass"
        ? "✅"
        : r.status === "fail"
          ? "❌"
          : "⚠️";
    const statusLabel = canaryFired ? "expected" : r.status;
    lines.push(
      `| \`${r.id}\` | ${r.severity} | ${statusIcon} ${statusLabel} | ${r.violations.length} |`,
    );
  }

  const failures = results.filter((r) => r.status === "fail");
  if (failures.length > 0) {
    lines.push("", "### Violations", "");
    for (const r of failures) {
      lines.push(`**${r.id}** (${severityBadge(r.severity)})`);
      const limit = Math.min(r.violations.length, 10);
      for (let i = 0; i < limit; i++) {
        const v = r.violations[i];
        lines.push(`- \`${v.repo}\` — \`${v.file}:${v.line}\` — ${v.detail}`);
      }
      if (r.violations.length > 10) {
        lines.push(`- _...and ${r.violations.length - 10} more_`);
      }
      lines.push(`> ${r.message}`, "");
    }
  }

  lines.push("---", "_Generated by Cross-Repo Invariant Verifier_");
  return lines.join("\n");
}

// ---------------------------------------------------------------------------
// Exit code logic
// ---------------------------------------------------------------------------

export function exitCodeForReport(report: VerificationReport): number {
  const hasBlocking = report.results.some(
    (r) =>
      r.status === "fail" &&
      !r.id.startsWith("canary") &&
      (r.severity === "critical" || r.severity === "high"),
  );
  if (hasBlocking) return 1;
  // Per-invariant errors (truncation, search failures, dead canary) mean the
  // run is incomplete — infrastructure failure, never a silent pass.
  const hasErrors = report.results.some((r) => r.status === "error");
  return hasErrors ? 2 : 0;
}
